version: "3"
services:
  mysqldatabase:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD= "test"
      - MYSQL_DATABASE= "test"
    networks:
      databases:
        ipv4_address: 192.168.69.10
    volumes:
      - testdatabase:/var/lib/mysql
  nodejsbackend:
    image: laaledesiempre/docker-express-mysql/express
    networks:
      databases:
        ipv4_address: 192.168.69.11
  reactfrontend:
    image: laaledesiempre/docker-express-mysql/react
    networks:
      databases:
        ipv4_address: 192.168.69.12
networks:
  databases:
    ipam:
      driver: default
      config:
        - subnet: "192.168.69.0/24"
