version: "3"
services:
  mysql:
    image: mysql
    environment:
      - MYSQL_DATABASE=db
      # So you don't have to use root, but you can if you like
      - MYSQL_USER=user
      # You can use whatever password you like
      - MYSQL_PASSWORD=password
      # Password for root access
      - MYSQL_ROOT_PASSWORD=password 
      - MYSQL_ROOT_HOST=%
    networks:
      databases:
        ipv4_address: 192.168.69.10
  express:
    build: ../express-mysql-server/
    depends_on:
      - mysql
    networks:
      databases:
        ipv4_address: 192.168.69.11
  react:
    build: ../database-front/ 
    ports:
      - "5173:5173"
    networks:
      databases:
        ipv4_address: 192.168.69.12
  nginx:
    build: ../nginx_server/
    depends_on:
      - express
    ports:
      - "3000:3000"
    networks:
      databases:
        ipv4_address: 192.168.69.15
networks:
  databases:
    ipam:
      driver: default
      config:
        - subnet: "192.168.69.0/24"
