 # https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-deployment 
  namespace: default
  labels:
    app: express  
spec:
  selector:
    matchLabels:
      app: express 
  replicas: 1
  template:
    metadata:
      labels:
        app: express  
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name: express 
        image: laaledesiempre/docker-express-mysql:express
        imagePullPolicy: Never
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 3000
---
# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: express 
  namespace: default
spec:
  selector:
    app: express 
  type: LoadBalancer
  ports:
  - name: 
    protocol: TCP
    port: 3000
    targetPort: 3000
---

 
